#!/usr/bin/env -S perl ${HOME}/.dotfiles/install --file

[run]
sudo apt update
sudo apt upgrade

# Get docker using the convenience script
curl -fsSL https://get.docker.com -o get-docker.sh
sudo sh get-docker.sh

# Install packages
sudo apt install ufw libffi-dev libssl-dev python3 python3-pip
sudo pip3 install docker-compose

sudo apt install fish 