#!/usr/bin/env -S perl ${HOME}/.dotfiles/install --file

[symlink]
.: ~/.config/fish

[run]
# Fetching fisher
fish -c 'curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher'

# Installing 'done'
fish -c 'fisher install franciscolourenco/done'
# Installing os-specific dependencies of done
fish -c 'if test (uname -s) = "Darwin"; brew install terminal-notifier; end'

# Priming done.fish
fish -c 'source ~/.config/fish/conf.d/done.fish;'

# Disabling fish motd
fish -c 'set -U fish_greeting'